### ISSUE TITLE
Homework 1: Trying out bril

### ISSUE THREAD

**Issue by jiangqucheng** [jiangqucheng/EECE7398_ST_Compiler#2]
# Homework 1: Trying out bril
You will write a blog post and put in in github using a pull request.
Then will put the name of the blog post into canvas.
You can ask questions on [Github Discussions](https://github.com/normrubin/normrubin.github.io/discussions).
Your goal is to get familiar with [Bril](https://github.com/sampsyo/bril).

## Part 1

- [x] Write a new benchmark.
- [x] You can write it by hand, use the [TypeScript compiler](https://capra.cs.cornell.edu/bril/tools/ts2bril.html), or generate it some other way. Try running it with [`brili`](https://capra.cs.cornell.edu/bril/tools/brilirs.html).
- [x] Open a pull request to add your new benchmark. ??? Add your code to the the [benchmarks directory](https://github.com/sampsyo/bril/tree/main/benchmarks).
- [x] Use `turnt --save yours.bril` to create the test outputs for your new benchmark. (See the [Turnt README](https://github.com/cucapra/turnt) for details.) 
- [x] Mention it in the [docs](https://github.com/sampsyo/bril/blob/main/docs/tools/bench.md).

## Part 2

- [x] Write a program to analyze or transform Bril programs in some small way. Pick your favorite programming language, there is no “starter code”, so you can start from scratch.
- [x] Load up a JSON file. You can start with [this](https://github.com/sampsyo/bril/blob/main/test/parse/add.json) tiny one! 
- [x] Read the [docs](https://capra.cs.cornell.edu/bril/).
- [x] Do something unambitious with it: count the number of add instructions, or add a print instruction before every jump, or whatever. Pick something small and contrived! 
- [x] Use [Turnt](https://github.com/cucapra/turnt) to test your new tool.
_Along the way, you will run into problems! Ask questions on [Github Discussions](https://github.com/normrubin/normrubin.github.io/discussions), and open issues and pull requests to describe or fix problems. For example, even super simple benchmarks you might imagine probably can’t be written easily because Bril is too simple. Mention this on [Github Discussions](https://github.com/normrubin/normrubin.github.io/discussions), and consider pitching in to help add features._
- [x] Think about how to write a good test, and finally write a post describing your work and submit it to github and submit the name to canvas.

**Comment by jiangqucheng** [comment]
[**Report** - Homework 1: Exploring Bril ](https://github.com/jiangqucheng/EECE7398_ST_Compiler/blob/b9c84cafb0e2122a2162ac9f9760ac559b9f6b2c/HW1/README.md)
