### ISSUE TITLE
Homework 2: Local Optimizations

### ISSUE THREAD

**Issue by jiangqucheng** [jiangqucheng/EECE7398_ST_Compiler#3]
# Homework 2: Local Optimizations

## Part 1

- [x] Implement 'trivial' dead code elimination in which you delete instructions that are never used before they are reassigned.

## Part 2

- [x] Implement local value numbering. 
- [x] Try pairing it with your dead code elimination code. 
- [x] Way and evidence that ensure implementation is correct and actually optimizes programs.
- [x] You might want to use the Brench program
- [x] for extra points: extend your implementation to handle some of the trickier examples talked about in class.

## Writing

- [x] Result as a blog post.
- [x] Part 2 : include evidence that your implementation is correct and actually optimizes programs.
